"""empty message

Revision ID: 2d8fd02c15c0
Revises: d3dc3dd83cbd
Create Date: 2018-03-09 13:50:33.983382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d8fd02c15c0'
down_revision = 'd3dc3dd83cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urinfo')
    op.add_column('admission', sa.Column('trinfo_id', sa.Integer(), nullable=True))
    op.drop_constraint('admission_ibfk_2', 'admission', type_='foreignkey')
    op.create_foreign_key(None, 'admission', 'trinfo', ['trinfo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('admission', 'tinfo_id')
    op.add_column('trinfo', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trinfo', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trinfo', type_='foreignkey')
    op.drop_column('trinfo', 'user_id')
    op.add_column('admission', sa.Column('tinfo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admission', type_='foreignkey')
    op.create_foreign_key('admission_ibfk_2', 'admission', 'tinfo', ['tinfo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('admission', 'trinfo_id')
    op.create_table('urinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['tlevel.id'], name='urinfo_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['tsubject.id'], name='urinfo_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='urinfo_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
