"""empty message

Revision ID: 368fe84fbd16
Revises: 
Create Date: 2018-02-10 22:21:06.632609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368fe84fbd16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_test_addtime'), 'test', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_addtime'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
