"""initial migration

Revision ID: bb1d49380854
Revises: 
Create Date: 2018-03-07 10:52:48.760127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1d49380854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refbook', sa.Column('info', sa.String(length=20000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refbook', 'info')
    # ### end Alembic commands ###
