"""empty message

Revision ID: cea79c16116a
Revises: bb1d49380854
Create Date: 2018-03-08 17:57:43.934527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea79c16116a'
down_revision = 'bb1d49380854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trinfo', sa.Column('tinfo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trinfo', 'tinfo', ['tinfo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trinfo', type_='foreignkey')
    op.drop_column('trinfo', 'tinfo_id')
    # ### end Alembic commands ###
