"""empty message

Revision ID: d3dc3dd83cbd
Revises: cea79c16116a
Create Date: 2018-03-08 18:07:42.229763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3dc3dd83cbd'
down_revision = 'cea79c16116a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trinfo_ibfk_1', 'trinfo', type_='foreignkey')
    op.drop_constraint('trinfo_ibfk_2', 'trinfo', type_='foreignkey')
    op.drop_column('trinfo', 'subject_id')
    op.drop_column('trinfo', 'level_id')
    op.drop_column('trinfo', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trinfo', sa.Column('price', mysql.FLOAT(), nullable=True))
    op.add_column('trinfo', sa.Column('level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('trinfo', sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('trinfo_ibfk_2', 'trinfo', 'tsubject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('trinfo_ibfk_1', 'trinfo', 'tlevel', ['level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
