"""empty message

Revision ID: dace8b10b26b
Revises: 16f5af002350
Create Date: 2018-02-28 12:58:37.280636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dace8b10b26b'
down_revision = '16f5af002350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_status')
    # ### end Alembic commands ###
